# @package _global_
optimizer_id: HEBO
optimizer_container_id: HEBO
hydra:
  job_logging:
    handlers:
      file:
        filename: ${hydra.runtime.output_dir}.log
loggers:
  - _target_: carps.loggers.file_logger.FileLogger
    _partial_: true
    overwrite: true
optimizer:
  _target_: leanhebo_carps.timing.timed_optimizer
  _partial_: true
  optimizer_id: ${optimizer_id}
  optimizer:
    _target_: leanhebo_carps.upstream.UpstreamHEBOOptimizer
    _partial_: true
    seed: ${seed}
    hebo_cfg:
      model_name: gp
      rand_sample: null
      acq_cls:
        _target_: hebo.acquisitions.acq.MACE
        _partial_: true
      es: nsga2
      model_config: null
      scramble_seed: ${seed}
